/**
 * TypeScript definitions for the tauri-plugin-whisper-rs.
 * These definitions match the Rust backend's camelCase serialization.
 */

import { UnlistenFn } from "@tauri-apps/api/event";

/**
 * Payload required to initialize the Whisper engine.
 */
export interface InitializeRequest {
  /** The absolute disk path to the Whisper .bin model file. */
  modelPath: string;
}

/**
 * Payload for processing raw PCM audio data directly.
 */
export interface TranscriptionRequest {
  /** Raw audio samples in f32 format. */
  audioData: number[];
  /** Optional patience factor for the beam search algorithm. */
  patience?: number;
  /** Optional number of beams for the search (higher is more accurate but slower). */
  beamSize?: number;
  /** Optional ISO 639-1 language code (e.g., 'en', 'tr', 'auto'). */
  language?: string;
}

/**
 * Payload for processing an audio file from the filesystem.
 */
export interface TranscriptionFileRequest {
  /** The absolute disk path to the audio file (supports mp3, wav, m4a, etc.). */
  audioPath: string;
  /** Optional patience factor for the beam search algorithm. */
  patience?: number;
  /** Optional number of beams for the search. */
  beamSize?: number;
  /** Optional ISO 639-1 language code. */
  language?: string;
}

/**
 * The resulting transcription content or error details.
 */
export interface TranscriptionResponse {
  /** The full text generated by the model. Null if an error occurred. */
  text: string | null;
  /** A descriptive error message. Null if the operation was successful. */
  error: string | null;
}

/**
 * Basic status response for setup and cleanup commands.
 */
export interface GenericResponse {
  /** Whether the operation was completed successfully. */
  status: boolean;
  /** Additional information or error reason. */
  message: string;
}

/**
 * Initializes the backend Whisper context with a model.
 * @param payload InitializeRequest
 */
export function initialize(
  payload: InitializeRequest,
): Promise<GenericResponse>;

/**
 * Transcribes audio data provided as a number array.
 * @param payload TranscriptionRequest
 */
export function transcribe(
  payload: TranscriptionRequest,
): Promise<TranscriptionResponse>;

/**
 * Transcribes an audio file directly from the given path.
 * @param payload TranscriptionFileRequest
 */
export function transcribeFromFile(
  payload: TranscriptionFileRequest,
): Promise<TranscriptionResponse>;

/**
 * Releases model resources and clears memory.
 */
export function release(): Promise<GenericResponse>;

export function listenTotalProcess(
  callback: (n: number) => void,
): Promise<UnlistenFn>;

export function listenProcess(
  callback: (n: number) => void,
): Promise<UnlistenFn>;

export function listenTranscription(
  callback: (t: string) => void,
): Promise<UnlistenFn>;
